name: Word Count Pipeline

on:
  workflow_call:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker Image
      run: docker build -t myacrdemo.azurecr.io/wordcount:latest .

    - name: Push Docker Image to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login myacrdemo.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker push myacrdemo.azurecr.io/wordcount:latest
